import { WhatsAppManager } from './services/WhatsAppManager';
import { CampaignScheduler } from './services/CampaignScheduler';
import { WarmUpService } from './services/WarmUpService';
import { InboxManager } from './services/InboxManager';
declare let whatsappManager: WhatsAppManager;
declare let campaignScheduler: CampaignScheduler;
declare let warmUpService: WarmUpService;
declare let inboxManager: InboxManager;
export declare function setupIPCHandlers(): void;
export { whatsappManager, campaignScheduler, warmUpService, inboxManager };
